#!/bin/bash

# Clean Architecture Migration Helper Script
# This script helps migrate from legacy code to clean architecture

echo "🏗️  Clean Architecture Migration Helper"
echo "======================================"

echo ""
echo "📁 Current Clean Architecture Structure:"
echo ""
echo "✅ Domain Layer (Core Business Logic):"
echo "   - Entities: Event, Product, Customer, Order, CheckIn, Package, LeaderboardEntry"
echo "   - Value Objects: LocalizedText, DateRange"
echo "   - Repository Interfaces: All defined"
echo "   - Domain Types: Centralized type definitions"
echo ""
echo "✅ Application Layer (Use Cases & Services):"
echo "   - Use Cases: Complete for all entities"
echo "   - Application Services: Complete orchestration services"
echo ""
echo "✅ Infrastructure Layer (External Concerns):"
echo "   - Repository Implementations: All implemented"
echo "   - Database Configuration: Moved to infrastructure"
echo "   - Legacy Adapters: Available for gradual migration"
echo ""
echo "✅ Presentation Layer (UI & API):"
echo "   - Clean Server Actions: Available in presentation/server-actions"
echo ""

echo ""
echo "🔄 Migration Status:"
echo ""
echo "✅ COMPLETED:"
echo "   - Server Actions: src/lib/data/clean-actions.ts → src/presentation/server-actions/clean-actions.ts"
echo "   - Database Config: src/lib/database → src/infrastructure/database"
echo "   - Legacy Postgres: src/lib/data/postgres.ts → src/infrastructure/adapters/legacy-postgres-adapter.ts"
echo "   - Domain Types: Centralized in src/domain/types"
echo ""

echo "🔄 IN PROGRESS:"
echo "   - Legacy Services: src/services/* (marked deprecated, use src/application/services/*)"
echo "   - Legacy Actions: src/lib/data/actions.ts (marked deprecated)"
echo ""

echo "⏳ TODO:"
echo "   - Update React components to use clean architecture imports"
echo "   - Migrate remaining type definitions"
echo "   - Remove legacy code once migration is complete"
echo ""

echo ""
echo "🚀 How to Use Clean Architecture:"
echo ""
echo "1. For new features, import from the main barrel export:"
echo "   import { EventApplicationService } from '@/clean-architecture';"
echo ""
echo "2. For server actions, use the clean actions:"
echo "   import { createEventAction } from '@/presentation/server-actions/clean-actions';"
echo ""
echo "3. For React components, use clean server actions:"
echo "   const handleSubmit = async (formData: FormData) => {"
echo "     await createEventAction(formData);"
echo "   };"
echo ""

echo ""
echo "📚 Documentation:"
echo "   - src/README-CLEAN-ARCHITECTURE.md - Complete organization guide"
echo "   - docs/CLEAN_ARCHITECTURE.md - Detailed implementation guide"
echo "   - docs/CLEAN_ARCHITECTURE_MIGRATION.md - Migration status"
echo ""

echo ""
echo "🔧 Available Commands:"
echo "   npm run typecheck  - Check TypeScript types"
echo "   npm run lint       - Run ESLint"
echo "   npm run dev        - Start development server"
echo "   npm run build      - Build for production"
echo ""

echo "✨ Clean Architecture is now organized and ready to use!"
echo "   Start by using the clean server actions for new features."
echo "   Gradually migrate existing code when making changes."
