name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/myapp

          # 1. Create/overwrite .env from GitHub secrets
          cat > .env <<EOL
          NODE_ENV=${{ secrets.ENV_NODE_ENV }}
          DATABASE_URL=${{ secrets.ENV_DATABASE_URL }}
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.ENV_NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.ENV_NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          EOL

          # 2. Pull latest code and rebuild
          git pull origin main
          docker compose down
          docker compose build --no-cache
          docker compose up -d
          docker system prune -af
