name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/myapp

          # 1. Sync .env.prod from GitHub secrets
          cat > .env.prod <<EOL
          # PRODUCTION ENVIRONMENT VARIABLES
          DATA_SOURCE=prisma
          ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
          ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }}
          NODE_ENV=production
          NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          DIRECT_URL=${{ secrets.DIRECT_URL }}
          EOL

          # 2. Make sure repo is clean and up to date
          git fetch origin main
          git reset --hard origin/main

          # 3. Build image with a unique tag (avoids downtime during build)
          DEPLOY_TAG=$(date +%s)
          docker compose build --no-cache --build-arg TAG=$DEPLOY_TAG

          # 4. Run database migrations
          docker compose run --rm app npx dotenv -e .env.prod -- npx prisma migrate deploy

          # 5. Replace running container with new one
          docker compose up -d --no-deps app

          # 6. Cleanup old images
          docker image prune -af
