name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/myapp

          # 1. Sync .env from GitHub secrets
          cat > .env <<EOL
          NODE_ENV=${{ secrets.ENV_NODE_ENV }}
          DATABASE_URL=${{ secrets.ENV_DATABASE_URL }}
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.ENV_NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.ENV_NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          EOL

          # 2. Make sure repo is clean and up to date
          git fetch origin main
          git reset --hard origin/main

          # 3. Build image with a unique tag (avoids downtime during build)
          DEPLOY_TAG=$(date +%s)
          docker compose build --no-cache --build-arg TAG=$DEPLOY_TAG

          # 4. Start a temporary container from the new image
          docker compose run --rm app npx prisma migrate deploy

          # 5. Replace running container with new one
          docker compose up -d --no-deps app

          # 6. Cleanup old images
          docker image prune -af
